### DISCUSSION TITLE
Proposal: modifiers for time comparisons

### DISCUSSION THREAD

**Discussion by Res260** [SigmaHQ/sigma-specification#137] [Ideas]
Proposal for a set of modifiers to allow for conditions on datetime fields.

I suggest adding the following modifiers:

`|minutes`: Get the number of minutes in the hour of the datetime field. Between 0 and 59
`|hour`: Get the number of hours in the day of the datetime field. Between 0 and 23
`|day`: Get the number of days in the month of the datetime field. Between 1 and 31
`|dayofweek`: Get the day of week as a number of the datetime field. Between 1 and 7 where 1 is monday and 7 is sunday.
`|week`: Get the week of year as a number of the datetime field. Between 1 and 52.
`|month`: Get the number of months in the year of the datetime field. Between 1 and 12.
`|year`: Get the year number of the datetime field.

## Example use case

Let's say I want to create a use case to detect when a user gets added to a specific group off-hours. This is currently impossible. The proposal would allow such use cases. It would look something like this:

```yaml
detection:
  selection:
    Operation: User Added to Group
    Group: Special Group
  time_selection_1:
    Timestamp|hour|gt: 17
  time_selection_2:
    Timestamp|hours|lt: 8
  condition: selection and (time_selection_1 or time_selection_2)
```

## Most SIEM support these operations

Splunk: With `strftime()`
Sentinel: With functions such as `hourofday()`
QRadar: With `DATEFORMAT()`
Elastic: With `DATE_FORMAT()`
Logscale: With `formatTime()`

Thoughts?

**Comment by thomaspatzke** [comment]
There's an use case, there are solutions for various SIEMs. Why not 😁

**Comment by frack113** [comment]
How write before 08h30 and after 17h00 (Monday to Friday except vacations 😄 ) ?
```yaml
selection_coffee:
    Timestamp|hour|lt: 08
    Timestamp|minute|lt: 30
```
I think SIEM will only check 00h00/00h29 -> 07h00-07h29
somethink like that ?
```yaml
selection_coffee:
    Timestamp|timecheck|lt: 08h30
    Timestamp|cron|lt: '30 8 * * * ' 
```

Why not add to  Meta Rule  `event_time` ?
I think it will be more easier
```yaml
correlation:
type: event_time
  rules:
    - add_special_group
  ???
  condition:
   ???
```

**Reply by Res260** [reply]
Interesting ideas. With my current proposal, if you'd like to check that the event is between 00:00 and 08:30, you'd have to do something like:

```yaml
detection:
  time1:
    Timestamp|hour: 8
    Timestamp|minute|lt: 30
  time2:
    Timestamp|hour|lt: 8
  condition: time1 or time2
```

So it's definitely possible, but I agree that it's perhaps not the most readable implementation.

For the `timecheck` proposal, it would also need to work with other things than days. Maybe we want an alert to raise during the summer only. This makes me think that I should add `dayofweek` and `week`. I'll update the original post.

For the `cron` proposal, I'm not sure how easy it's going to be to parse and work with.

For the correlations proposal, IMO it adds a bit much of complexity having to deal with multiple YAML documents for simple conditions like this.

@thomaspatzke thoughts?

**Reply by frack113** [reply]
The cron version is more my sadistic side than a real solution.
I was think of a meta rule as many rules can usefull only outside business hours .
You set the time conditon only once , and add the rules id (or name ) to the `rules` section.
Each rule in the rules section must have a unique output in that case with the correct time.

**Reply by frack113** [reply]
I'd like to keep detection and context separate.
Was thinking, if you want to keep it in the rule:
```yaml
time_context:
   time_1:
       field: Timestamp
       day:
           - monday
           - wednesday
        start : 00h00
        end: 08h30
    time_2:
       field: Timestamp
       day:
           - monday
           - wednesday
        start : 17h00
        end: 24h00
     time_3:
       field: Timestamp
       day:
           - sunday
        start : 00h00
        end: 24h00
    condition: 1 of time_*
detection:
    selection:
        azerty
    condition: selection
```
final_query = time_context AND detection

more elegant
```yaml
time_context:
   field: Timestamp
   time_1:
       day, end start
   condition:
```
