### DISCUSSION TITLE
Proposal: new aggregate functions in correlation rules

### DISCUSSION THREAD

**Discussion by Res260** [SigmaHQ/sigma-specification#166] [Ideas]
## Context
Right now, correlations searches only support "COUNT" as an aggregation function

## Proposal 
There exists many more, like "SUM", "AVERAGE", "MAX", "MIN", "MEDIAN", "MODE", "PERCENTILE", "RANGE" and "STANDARD DEVIATION".

This sounds like a lot, but for most backends, the resulting rule would be the same for all of these, just the aggregate functions that changes.

## What this would allow

This would allow to create Sigma Correlations rules like those:
- At least 1000MB was sent to a website in the span of 1 day by a single user.
- A computer spawned more processes in a day than 99% of the other computers.
- More than half of the exit codes of the IIS process were non-zero.

etc.

## Proposed implementation

Here is my proposed implementation for the rule "At least 1000MB was sent to a website in the span of 1 day by a single user."
```yaml
title: At least 1000MB was sent to a website in the span of 1 day by a single user.
id: c167d0df-442a-4410-9b48-0a384b679116
status: stable
level: medium
correlation:
  type: sum  # <-- Could be any choice of sum, average, max, min, median, mode, percentile, range, standard_deviation
  rules: 
    - request_to_website
  group-by:
    - domainName
    - Username
  timespan: 24h
  condition:
    gte: 1000000000
    field: BytesOut
---
title: Single request to a website
name: request_to_website
id: 24b39749-f29a-4bfe-a852-21a3327f8c5a
logsource:
  category: Web Proxy
detection:
  selection: 
    Event: 'Request'
  condition: selection
```

This requires very little change to the specification to allow such rules. We simply allow these new types.

Here is the "A computer spawned more processes in a day than 99% of the other computers." example:

```yaml
title: A computer spawned more processes in a day than 99% of the other computers.
id: c167d0df-442a-4410-9b48-0a384b679116
status: stable
level: medium
correlation:
  type: percentile
  rules: 
    - process_creation
  group-by:
    - ComputerName
  timespan: 24h
  condition:
    gte: 99
---
title: A single process creation
name: process_creation
id: 24b39749-f29a-4bfe-a852-21a3327f8c5a
logsource:
  category: process_creation
detection:
  selection: 
    Event: 'process creation'
  condition: selection
```

```yaml
title: More than half of the exit codes of the IIS process were non-zero.
id: c167d0df-442a-4410-9b48-0a384b679116
status: stable
level: medium
correlation:
  type: median
  rules: 
    - end_of_process
  group-by:
    - ComputerName
  timespan: 24h
  condition:
    gt: 0
    field: ExitCode
---
title: A single end of process 
name: end_of_process
id: 24b39749-f29a-4bfe-a852-21a3327f8c5a
logsource:
  category: end_of_process
detection:
  selection: 
    Event: 'end of process'
  condition: selection
```

## Conclusion

Adding these to the Sigma Correlations Specification would allow many very interesting detections to be developed. At my organization, we strive to achieve 100% of our rules to be expressed in Sigma, and this would be a big step in this direction.
