### DISCUSSION TITLE
Field should be referenced as part of the possible "Value" comparison

### DISCUSSION THREAD

**Discussion by lcostantino** [SigmaHQ/sigma-specification#168] [Ideas]
This may have been previously asked or mentioned in #52.

It's pretty common to have rules that require comparison (with all supported operators) between fields for the same event.

Currently,  we are using some extension that if the "Value" match a FieldName if will be changed appropriately.

(In this "sample" syntax any string that starts with <,<,!=,=,<=,>= will be evaluated for a subsequent field name, but nothing prevent to use the same value replacement like cs-bytes|gte: "myField" , except for types check [int, string, etc])

Use cases would include:
->  connections with more traffic sent that received 
->  A low integrity process spawning a high integrity process
->  etc, etc..

Example:

```
            title: Test
            status: test
            logsource:
                category: network_connection
                product: windows
            detection:
                sel:
                     cs-bytes:
                       - ">sc-bytes"
                     pkt-count|gte: 3
                condition: sel
```

I'm just proposing the feature here, not the final syntax, but can work on that if there's agreement about this need.

**Comment by Res260** [comment]
There already exists a modifier to reference another field: `fieldref`.

However, it only works for "`fieldA` equals `fieldB`" comparisons AFAIK.

It does not have to be this way, though. 

This _should_ work and would not require new syntax or new modifiers:

```yaml
detection:
  selection:
    requestBytes|gte|fieldref: responseBytes
  condition: selection
```

This reads as "the number of requestBytes is greater or equal to the number of responseBytes"
