### DISCUSSION TITLE
Proposal: Sigma Defeats

### DISCUSSION THREAD

**Discussion by sifex** [SigmaHQ/sigma-specification#35] [Ideas]
Hi Team,

I've drafted the following proposal on a problem that I had at my previous role. Please let me know your thoughts and if there's anything you're currently doing to fill this gap.

---

## Proposal

Defeats are a way to collect and apply false positives to Sigma rules. 

### Abstract

Defeats are designed to sit alongside Rules as a method of preventing future false positives when implementing Sigma rules. They answer the question of:

> How do I as a Security Analyst prevent this rule from triggering on host XXXXXX.domain.com

or 

> How to I as a Security Analyst locally apply false positives to some client environments, and not to others? 

The advantages that Defeats have over using the existing `filter` strategy are:

- their scope can be localised to a client or SIEM instance, giving end-users the ability to prevent future false positives when implementing Sigma rules 
- they don't modify or impact on any existing Sigma rule, and provides a solution to those wanting to keep existing upstream Sigma repositories "as-is", and without local modification
- they can apply to multiple rules, de-duplicating existing filters across Sigma alerts

These are located in files separated from the Sigma rule itself. 

Defeats *can* but shouldn't replace the commonly seen pattern of including `filter` as a part of the Sigma rule. This strategy of using `filters` in a Sigma rule should be kept in-place, where everyone in the community can benefit from a contribution of a Pull Request to prevent known false positives.

### Naming

The name of a "Defeat" came from an analyst team "defeating" reoccurring false-positives as part of the tuning process. Name is not final and is likely to change in later revisions.

### Versioning

Defeats are proposed to be implemented in Sigma version 2 and above.

### Backwards compatibility

This proposal ensures backwards compatibility by not modifying the existing Sigma rule specification, and exists as an entirely optional feature. 

### Implementation 

Similar to other Sigma standards, Defeats are YAML files that would sit alongside a repository of rules, typically under the `defeats/` directory. They would supply information about when a given detection should not trigger.

Some examples of this could include:

- do not trigger against a Domain Controller based on hostname naming (for detections targeting Security Group additions and deletions)
- do not trigger against service the following service accounts, based on how clients name their service accounts

Defeats would act as a standard interface that backends can support within pySigma's pipeline hooks.

In the case of Splunk (or other backends that can include CSV lookups) their implementation strategy for defeats *could* include:

```spl
| search NOT [|inputlookup exclude_common_administration_accounts.csv]
```

as a method of not bloating out the search string itself. Other backends can inline Defeats within searches.

### Usage

Defeats should be applied by passing an additional optional flag to the `sigma-cli convert` command as `-D` or `--defeat`. 

The existing method of detection should be used as to not overcomplicate the intent to new users.

`ids` field is used to list the rules in which the defeats applies.

```yaml
# defeats/global/exclude_common_administration_accounts.yml
name: Exclude common administration accounts
description: ...
ids:
    - 12345678-bef0-4204-a928-ef5e620d6fcc # rules/windows/builtin/...
    - 91011121-bef0-4204-a928-ef5e620d6fcc # rules/windows/builtin/...
    - 31415161-bef0-4204-a928-ef5e620d6fcc # rules/windows/builtin/...
detection:
    service_accounts:
        AccountName|startswith:
            - SVC_
    condition: not service_accounts
```

Applied to an existing rule, you would see the following after conversion.

**Basic Interpretation**

---

```splunk
index="..." EventCode=123
| search NOT AccountName="SVC_*"
```

**Complex Interpretation**

```splunk
index="..." EventCode=123
| search NOT [|inputlookup exclude_common_administration_accounts.csv]
```

### Challenges

- Field Names / Validation across rules
- Keeping v1 unaffected by keeping existing `filter` in rules (essentially don't remove)
- Communication and Integration with existing pySigma Backends / pySigma probing whether the backend fully supports this feature.

### Development

The following developers take on the responsibility of providing the PR as part of pySigma. 

- Alex (@sifex)

### Contribution

This proposal welcomes any feedback / changes. When doing so, please ensure constructive feedback if at all possible.

**Comment by nasbench** [comment]
First of all thanks for your contribution and an Interesting proposal indeed. I have a couple of questions first.

1st point is who would provide these "defeats"? Because from what I Understand these are specific to organizations and how they want to apply (or in this case not apply) certain rules depending on certain conditions. Basically, it requires specific knowledge of the org itself. So it cannot be community driven to a certain extent. And in the case where the "defeat" condition is "generic" enough it would be equal to a filter since it would be considered an FP to the rule.

2nd point is. Why make it part of SIGMA if it's specific and different on an org-by-org basis and also backend-dependent? Meaning why would someone write in SIGMA rather than his own backend language?

I think of this as typical work of detection/analyst teams. They know their env the best and they choose to apply or remove certain rules based on their knowledge and the tools available to them from a backend perspective (similar to how you showed the example with Splunk).

Please correct me if I'm wrong in my understanding.

Cheers.

**Reply by sifex** [reply]
Yea all good points. I think the only reason why this comes into major relevancy is that the whole `Ctrl+C` & `Ctrl+V` nature of Sigma rules is archaic, and CI/CD methodologies are making their way into our SOCs, as well as others. 

To answer both points, this resolves the issue of:

> I have 10 Sigma rule repos, containing exactly which rules best apply to each client (including paid and custom rules), all continuously deploying out to 10 different SIEMs using Gitlab/Github CI. Where do I as an analyst add my false positives? I can append them to the end of the query using some hack, but then I don't get field mapping for that logsource. Do we manually convert them when it comes to deploying them? What happens if a lead forgets to add / removes / typos the FP snippet?"

The reason why this should be a part of Sigma is imho Sigma backends now have the ability - and strong encouragement - to deploy straight to the SIEM (using API calls for the most part) thanks to pySigma. You can see this need in [SEIGMA](https://github.com/3CORESec/SIEGMA) and [Sigma2SplunkAlert](https://github.com/P4T12ICK/Sigma2SplunkAlert) for this to become standard, just in Splunk alone.

---

Opinion (separate from Proposal, but maybe provides context).

I'm definitely over in On-Prem land where this stuff is definitely more prevalent than cloud.

Sigma's future has the ability to streamline the workflow for thousands of SOCs. You have one repository per client - filled with rules, defeats, workflows, notes, lookups - all continually being contributed by your analyst & detection teams, updates made over - and reviewed using PRs, and deployed out to your SIEM automatically, possibly even validating rules against known true-positive log snippets as part of your test suite. 

Edit: Defeats are also probably just syntactical sugar for what Sigma Rule implementators are going to have to do with pySigma piplines anyway using wildcards.

**Comment by frack113** [comment]
For me there are 3 completely different things:
- the sigma specification
- the rule deposit
- the conversion tools 

Having a way to manage not filter but specific FP  in the specifications is a good thing.

```yaml
name: Exclude common administration accounts
description:  WHY I do it 
ids:
    - 12345678-bef0-4204-a928-ef5e620d6fcc # rules/windows/builtin/...
    - 91011121-bef0-4204-a928-ef5e620d6fcc # rules/windows/builtin/...
    - 31415161-bef0-4204-a928-ef5e620d6fcc # rules/windows/builtin/...
logsource:
exclution:
    service_accounts:
        AccountName|startswith:
            - SVC_
```
- name  no comment
- description This is a good practice 
- ids would like to change for  something like rule/cover (IDS brings me back to my WAF , firewall dark age)
- logsource  I don't want someone make a windows exclution on auditd rules
- exclution I can only exclude local FP 

Usage Case:
I have a internal application with a powershell script that look like a APT and you can not kill the dev .
I will not make a PR on SigmaHQ , We are the only one with this application.

- Sigma Specification V1
I edit all the FP rule and  add a filter `filter_bad_script` with the name and path .
If the rule is updated, I have to do it again

- Sigma Specification V2
I edit a exclution file add the id of the FP rules.
If the rule is updated, I say my boss i have 2 days of works like in V1 

The converter should work "Signa condition AND NOT sigma exclution"

I want to keep this case as simple as possible.
If you have to make many exclusion for a rule , you should ask your self why.

**Reply by sifex** [reply]
🧡 Great additions, thanks for the feedback, I'll update it in a quick moment.

- **Re: converter**
  I'm really really torn on whether the design of Defeats should perform an inclusive or exclusive by default – <br />ie.<br />`selection not (defeat)` (negation implied) or<br />`selection (not defeat)` (negation explicit / with the "not" in the defeat itself).

  Mainly this is to avoid the double negative that happens when you want to **ONLY** include certain selections.

  I totally see why & where a defeat should lose the "not". I guess the thinking behind it is

  - How do people expect it to work without thinking about it,
  - How complicated does the negation of AND / OR operations become and
  - How much pain is there context switching behind thinking 
    - "OK, I'm writing a detection, so this is an inclusive search" vs 
    - "OK, I'm writing a defeat, this is an exclusive search, so they're technically a NOT in-front of everything I write (in brackets).

**Reply by sifex** [reply]
nvm I didn't see the field name `exclusion`. That makes sense to have `exclusion` (and by extension `inclusion`) so that it's clear what the defeat is doing.

Edit:

### Exclusion Example:

```yaml
# rules/example_rule.yml
logsource:
    product: windows
    service: security
detection:
    selection: 
        field: value
    condition: selection
```

```yaml
# defeat/default_exclusion_example.yml
name: Defeat Exclusion Example
description: Example description
ids:
    - 12345678-bef0-4204-a928-ef5e620d6fcc # rules/windows/builtin/...
logsource:
    product: windows
    service: security # Will throw a warning / fatal if the ID is not targeting this log-source.
exclude:
    excluded_hosts:
        ComputerName|startswith:
            - DEV_
            - TST_
```

```spl
index="win_security" source="WinEventLog:Security" field="value"
| search NOT ( host=DEV_* OR host=TST_* )
```


### Inclusion Example:

```yaml
# defeat/default_inclusion_example.yml
name: Defeat Inclusion Example
description: Example description
ids:
    - 12345678-bef0-4204-a928-ef5e620d6fcc # rules/windows/builtin/...
logsource:
    product: windows
    service: security # Will throw a warning / fatal if the ID is not targeting this log-source.
include:
    included_hosts:
        ComputerName|startswith:
            - PROD_
            - STAG_
```

```spl
index="win_security" source="WinEventLog:Security" field="value"
| search ( host=PROD_* OR host=STAG_* )
```

**Reply by frack113** [reply]
For me "defeat" don't have a condition, so to keep it simple
```yaml
action: include/exdude
selection: <= need a better name to avoid someone think it the same selection from rule :)
   fieldname|contains: only_you
``` 
so the converter can say I have my condition "A" with action I know if I must "and" or "and not" the "selection" part.

I would like to keep with a single selection (can be a list )
