### DISCUSSION TITLE
Reference to other rules in the condition of a detection

### DISCUSSION THREAD

**Discussion by Res260** [SigmaHQ/sigma-specification#6] [Ideas]
Hello (again), I'm (still) building a custom backend for QRadar and I sometimes get roadblocks related to limitations in the Sigma specification. Now I know my usecase stretches a bit what Sigma was built for, my use case being to use Sigma as part of a complete detection-as-code pipeline, where rules are versionned in a git repo, reviewed, then automatically converted to the target SIEM and deployed automatically. So, this is only a suggestion that, I think, could help with this use-case, I understand if you think this would not fit within the Sigma spec.

I'd like to be able to reference another rule in the `condition` section of a sigma `detection`, such as:
```yaml
title: Test rule2
status: stable
logsource:
  product: Something
detection:
  selection:
    somefield: somevalue
  condition: selection and ($rule:Some Other Rule Name)
```
Where the rule `Some other rule name` would be in a different file, possibly.

I'm aware that [Rule Collections](https://github.com/SigmaHQ/sigma/wiki/Specification#rule-collections) exist, but there are two limitations that prevent me from using this:
1. They need to be in the same yaml document
2. They create an independant rule (in the parsed `SigmaRule`, there is no reference that this rule was built from another rule part ), which can't be used to re-use parts of detections in the SIEM.

My use case is QRadar's Building Blocks (BBs), a detection rule that is meant to be reused with other rules. For performance reasons, I'd like to reproduce this behavior with sigma, but right now, my solution is to break the specification with something like:

```yaml
title: Test rule2
status: stable
logsource:
  product: Something
detection:
  selection:
    somefield: somevalue
  selection2:
    BB: NameOfTheRule
  condition: selection and (selection2)
```

I'll keep my solution if my idea is not a good fit for Sigma, but I'd like to stay as close as the specification as possible :)

**Comment by frack113** [comment]
Can you check https://github.com/SigmaHQ/sigma-specification ?

https://github.com/SigmaHQ/sigma-specification/blob/main/wip/Sigma_Correlations.md

**Comment by Neo23x0** [comment]
@frack113 He already mentioned that he has checked the specifications and the correlations and couldn't find coverage for his use case

@Res260 We don't want references from one rule to another because it's a PITA when handling the rules. The advantages of not having rules referencing to each other in conditions clearly outweigh the few disadvantages and rare corner cases like yours.

**Comment by Res260** [comment]
I understand, thanks for your reply!

**Comment by Neo23x0** [comment]
I wonder if you could do what you want to do with an additional field, because the specification allows for additional custom fields on the root level of the rules. 

e.g. 
```yaml
title: Test rule2
status: stable
logsource:
  product: Something
detection:
  selection:
    somefield: somevalue
  condition: selection and (selection2)
import_rules:
   rules: 
      - NameOfTheRule
   append_condition: 'and NameOfTheRule'
```
