### DISCUSSION TITLE
`Data|contains|all` versus `'|all':` ?

### DISCUSSION THREAD

**Discussion by YamatoSecurity** [SigmaHQ/sigma-specification#84] [Q&A] [answered]
Some rules use `Data|contains|all` to specify a list of keywords that all need to be present somewhere in the log (any field):
```
detection:
    application:
        Channel: Application
    selection:
        Provider_Name: Windows Error Reporting
        EventID: 1001
        Data|contains|all:
            - MsMpEng.exe
            - mpengine.dll
    condition: application and selection
```

However, some rules use `'|all':` to also do the same thing (from my understanding):
```
detection:
    keywords_export_command:
        '|all':
            - 'New-ExchangeCertificate'
            - ' -GenerateRequest'
            - ' -BinaryEncoded'
            - ' -RequestFile'
    keywords_export_params:
        - '\\\\localhost\\C$'
        - '\\\\127.0.0.1\\C$'
        - 'C:\\inetpub'
        - '.aspx'
    condition: keywords_export_command and keywords_export_params
```
Is there a difference in the meaning or just two ways to write the same rule? (If so, should rules be re-written to follow a uniform syntax?)

The same thing also happens with `Data|contains`:
```
detection:
    selection:
        Provider_Name: 'MSSQLSERVER'
        EventID: 33205
        Data|contains:
            - 'statement:ALTER SERVER AUDIT'
            - 'statement:DROP SERVER AUDIT'
    condition: selection
```
and rules that don't specify a field:
```
detection:
    keywords:
        - 'dpapi::masterkey'
        - 'eo.oe.kiwi'  
        - 'sekurlsa::'
    condition: keywords
```

Are these the same meaning as well?
