### DISCUSSION TITLE
Suggestion: Default to Unquoted Strings in Sigma Specification

### DISCUSSION THREAD

**Discussion by Res260** [SigmaHQ/sigma-specification#93] [Ideas]
[The YAML specification 1.2.2 (latest)](https://yaml.org/spec/1.2.2/) specifies:

> 1.1. Goals
>The design goals for YAML are, in decreasing priority:
>**_1 YAML should be easily readable by humans._**
>2 YAML data should be portable between programming languages.
>3 YAML should match the [native data structures](https://yaml.org/spec/1.2.2/#representing-native-data-structures) of dynamic languages.
>4 YAML should have a consistent model to support generic tools.
>5 YAML should support one-pass processing.
>6 YAML should be expressive and extensible.
>7 YAML should be easy to implement and use.

Regarding strings, it also specifies:

> The plain (unquoted) style has no identifying [indicators](https://yaml.org/spec/1.2.2/#indicator-characters) and provides no form of escaping. **_It is therefore the most readable_**, most limited and most [context](https://yaml.org/spec/1.2.2/#context-c) sensitive [style](https://yaml.org/spec/1.2.2/#node-styles).

However, the [Sigma specification](https://github.com/SigmaHQ/sigma-specification/blob/main/Sigma_specification.md) asks for quotes for strings:

> The rule files are written in [yaml format](https://yaml.org/spec/1.2.2/) To keep the rules interoperable use the following:

> - UTF-8
> - LF for the line break (the Windows native editor uses CR-LF)
> - Indentation of 4 spaces
> - Lowercase keys (e.g. title, id, etc.)
> - **_Single quotes `'` for strings and numeric values don't use any quotes (if the string contains a single quote, double quotes may be used instead)_**

However, this only seems respected in the `selection`s block of the rules, as seen in the example rule:

```yaml
title: Whoami Execution
description: Detects a whoami.exe execution
references:
      - https://speakerdeck.com/heirhabarov/hunting-for-privilege-escalation-in-windows-environment
author: Florian Roth
date: 2019/10/23
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image: 'C:\Windows\System32\whoami.exe'      <-- ***Here***
    condition: selection
level: high
```

Since punctuation like quotes adds clutter to the rule, that all the fields in the rules don't use quotes for this reason, and to respect the first goal of YAML, **I suggest that the specification changes its guideline to the following**:

> The rule files are written in [yaml format](https://yaml.org/spec/1.2.2/) To keep the rules interoperable use the following:
> [...]
> - Do not use any quote for strings, unless it contains ` #` `'` `"`, it starts or end by white space caracters or the string starts with any of these caracters: `:` `?` `[` `]` `{` `}` `,` `&` `*` `!` `|` `>` `%` `@` `\n` `\r` `\t`. To use line feed (`\n`) or tab caracters (`\t`), use double quotes `"`. For any other case, use single quotes `'`. 

Example:
```yaml
title: Test rule
description: Test rule for specification
author: Émilio Gonzalez
date: 2023/07/19
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image: C:\Windows\System32\whoami.exe
        FileName: whoami.exe
        Author: "'threatactor1\t"
        DateWritten: 2023-01-14 12:34:56
        SomeOtherField: ':something:'
    condition: selection
level: high
```

This example is made to have all the quote possibilities, but realistically, **the vast majority of rules do not require quotes at all, which would make most sigma rules more readable**.
