### ISSUE TITLE
Feature Request: Custom Queries

### ISSUE THREAD

**Issue by WildDogOne** [SigmaHQ/sigma-specification#14]
Hey everyone,

I've been playing around with Sigma for our QRadar instllation.
And I've noticed that some queries just don't work (or at least I think that's how it is)
For example: if Value is Greater than X
or: if property is in reference set
and so on.
Now I am aware that QRadar is a bit of a special child so I don't think it would make sense to implement everything that QRadar does.

But might it be of interest to have the possibility to input statements directly in the language needed?

Example:
```
detection:
  selection:
    username: X
  timeframe: 1d
  condition: selection and confidence > 80
```

Right now I just put inline comments because we use sigma primarily for documentation
so I do this:
```
detection:
  selection:
    username: X
    #confidence > 80
  timeframe: 1d
  condition: selection
```

I hope someone understands what I mean 😄 

Regards,

Linus

**Comment by sifex** [comment]
We shoehorned this into our own `sigmac` wrapper a year or so ago. It didn't get a huge amount of uptake, but here's what we learnt at least when implementing across SIEMs.

- We used the special keyword `query` to indicate that the wrapper should not use the `sigmac` converter and instead only use the raw query instead. 
- The wrapper also did a lookahead for where the logsource shouldn't be prepended. In this case, `| tstats` shouldn't have `index=win* source="WinEventLog:System` prefix attached, but a regular Splunk search should have it. Each backend would essentially need to be aware of this.


```yaml
title: 'An example rule'
level: low
logsource:
  product: windows
  service: system
detection:
  query:
    splunk: >
      | tstats count where index="*" by _time, index
    sumologic: >
      (other query)
  condition: query
  timeframe: 30m
fields:
- index
```

In hindsight, I think a `detection.engine` to be `(sigma|raw)` (where sigma would use the `selection` and `condition` fields and `raw` would use the name of the SIEM) would be better suited. Maybe even have it apart of the new `schema` field in v2.

imho: I think Sigma should include this in v2 as a feature, but forbid it to be included in the common rule repos, and instead have it as a breakglass options for teams to be able to use locally. I can imagine once you make raw query sharing the norm, you end up having two problems

- it completely does away with the Sigma project's ethos in favor for more complete detection content repos (such as [`splunk/security_content`](https://github.com/splunk/security_content))
- it fractures the community back into their SIEM-specific query way of thinking, making sharing less automatic for Detection Engineers and Analysts
