### ISSUE TITLE
 Version 2.1 - New modifier to check if field is empty or null

### ISSUE THREAD

**Issue by frack113** [SigmaHQ/sigma-specification#142]
Add a new modifer to check if the field data is empty or null.
Some telemetry use `-` too 

* name: ?
* type: boolean

```yaml
    myfield|?: false
````
will cover 
```yaml
filter_null:
    myfield: null
filter_empty:
    myfield:  ''
    myfield: '-'
condition: not 1 of filter_*
````
