### ISSUE TITLE
Sigma_Correlations.md page "404 not found"

### ISSUE THREAD

**Issue by jiang834686379** [SigmaHQ/sigma-specification#94]
Hey, I'm trying to open the [Sigma_Correlations.md](https://github.com/SigmaHQ/sigma-specification/blob/main/wip/Sigma_Correlations.md) page on the[ Wiki](https://github.com/SigmaHQ/sigma/wiki) page to get some information about the usage of "Sigma correlations", but page displays as follows:
```
404 - page not found
The 
main

 branch of 
sigma-specification

 does not contain the path 
wip/Sigma_Correlations.md.
```

**Comment by jiang834686379** [comment]
I notice that Sigma 0.21 remove aggregation expression in Sigma rule file. Here is my old rule that uses the pipe symbol "|" for aggregation. How can I modify it using Sigma Correlations?
```
detection:
    condition:
      - selection1 and not filter | count(TargetUserName) by ProcessName > 10
    timeframe: 24h
    filter:
        ProcessName: '-'
    selection1:
        EventID: "4625"
```
